#!/bin/sh

#Genius or madness? I'm not sure.
# https://news.ycombinator.com/item?id=6897425
# Same idea as my old script 'freck'; but now piping to vim wiki.
# NB: prob an exceptionally bad idea if already open in vim

echo [` date  +%H:%M`]:`pwd`: $* "redirect to"  ~/vimwiki/diary/`date +%Y-%m-%d.wiki`
# Files look like 2012-04-25.wiki
